use std::error::Error;

pub fn open() -> Result<(), Box<dyn Error>> {
    Ok(())
}
